### ISSUE TITLE
开启后崩溃

### ISSUE THREAD

**Issue by kmvan** [ohyeah521/HexinNoAds#3]
Name : 同花顺至尊版 
Build version: V9.68.35 
Build date: 2019-04-04 11:10:49 
Current date: 2019-06-06 10:51:22 
Device: HTC U11 
 
Stack trace:  
java.lang.NoClassDefFoundError: cem$a
	at cem$a.a(HexinClass:988)
	at cem.a(HexinClass:140)
	at cna.a(HexinClass:40)
	at cqj.a(HexinClass:396)
	at cqj.b(HexinClass:471)
	at cqj.a(HexinClass:42)
	at cqj$2.a(HexinClass:153)
	at crl.c(HexinClass:1212)
	at crl.a(HexinClass:1183)
	at cqj.a(HexinClass:147)
	at cqj.a(HexinClass:42)
	at cqj$3.a(HexinClass:793)
	at crl.c(HexinClass:1212)
	at crl.a(HexinClass:1183)
	at cqj.b(HexinClass:784)
	at cqd.e(HexinClass:237)
	at cqd.b(HexinClass:213)
	at com.hexin.android.service.push.PushService.request(HexinClass:646)
	at com.hexin.android.service.push.PushService.heartbeat(HexinClass:586)
	at com.hexin.android.service.push.PushService.openPush(HexinClass:358)
	at com.hexin.android.service.push.PushConnect.notifyPushAuthSuccess(HexinClass:491)
	at csz.a(HexinClass:28)
	at cpg.a(HexinClass:30)
	at cpf.a(HexinClass:65)
	at crk.a(HexinClass:54)
	at cqy$1.run(HexinClass:125)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ExceptionInInitializerError
	at cem$a.a(HexinClass:988)
	at cem.a(HexinClass:140)
	at cna.a(HexinClass:40)
	at cqj.a(HexinClass:396)
	at cqj.b(HexinClass:471)
	at cqj.a(HexinClass:42)
	at cqj$2.a(HexinClass:153)
	at crl.c(HexinClass:1212)
	at crl.a(HexinClass:1183)
	at cqj.a(HexinClass:147)
	at cqj.a(HexinClass:42)
	at cqj$3.a(HexinClass:793)
	at crl.c(HexinClass:1212)
	at crl.a(HexinClass:1183)
	at cqj.b(HexinClass:784)
	at cqd.e(HexinClass:237)
	at cqd.b(HexinClass:213)
	at bja.a(HexinClass:357)
	at bja.a(HexinClass:373)
	at bja.b(HexinClass:536)
	at bja.b(HexinClass:468)
	at bja$1.run(HexinClass:289)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:307)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:302)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	... 1 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.substring(int, int)' on a null object reference
	at cqp.c(HexinClass:177)
	at cqp.a(HexinClass:240)
	at cem.p(HexinClass:162)
	at cem.<init>(HexinClass:145)
	at cem.<init>(HexinClass:81)
	at cem$a.<clinit>(HexinClass:989)
	... 28 more

**Comment by ohyeah521** [comment]
你先关闭xposed的插件试试，从日志看，感觉是它自身的bug，跟我的xposed插件无关，你可以测试一下

**Comment by kmvan** [comment]
禁用插件后ths就能正常开启了。

**Comment by kmvan** [comment]
看起来有点像跳过广告的功能引起的

**Comment by ohyeah521** [comment]
好奇怪，我这里目前正常，你发送logcat的完整日志来看看

**Comment by ohyeah521** [comment]
> 看起来有点像跳过广告的功能引起的

已经修复了，升级到最新版本就可以了

**Comment by kmvan** [comment]
感谢。但我手机不小心摔了，现在没法测试。T_T
是跳过广告的功能引起的吗？没有看源码，纯猜测。

**Comment by ohyeah521** [comment]
> 感谢。但我手机不小心摔了，现在没法测试。T_T
> 是跳过广告的功能引起的吗？没有看源码，纯猜测。

是的，你是用的edxposed吧，我在edxposed发现这个问题，xposed没问题

**Comment by kmvan** [comment]
是的，edxp只是过渡了。等xp作者弄pie版本后，就用回xp的

**Comment by ohyeah521** [comment]
> 是的，edxp只是过渡了。等xp作者弄pie版本后，就用回xp的

嗯，只能等xp作者更新了，edxp还行，太极比较垃圾
